name: Linting

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5.0.0
    - uses: pre-commit/action@v3.0.1
