name: Linting

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        python-version: ['3.8', '3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5.1.0
      with:
        python-version: ${{ matrix.python-version }}

    - run:  |
        python -m pip install --upgrade pip
        python -m pip install -U .[dev]

    - name: test
      run: |
          pytest --verbose --cov=desktop-notifier --cov-report=xml

    - name: Upload Code Coverage
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: pytest
        env_vars: OS,PYTHON,TYPE
        name: pytests
        token: ${{ secrets.CODECOV_TOKEN }}
      env:
        OS: ${{ matrix.platform }}
        PYTHON: ${{ matrix.python-version }}
