name: Linting

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        python-version: ['3.9', '3.12']
        include:
        - pre-command: ""

        - os: "ubuntu-latest"
          # Install blackbox to provide a lightweight window manager.
          pre-command: |
            sudo apt update -y
            sudo apt install -y --no-install-recommends blackbox

            # Start Virtual X server
            echo "Start X server..."
            Xvfb :99 -screen 0 2048x1536x24 &
            sleep 1

            # Start Window manager
            echo "Start window manager..."
            DISPLAY=:99 blackbox &
            sleep 1

    steps:
    - uses: actions/checkout@v4

    - name: set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v5.1.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: install dependencies
      run:  |
        ${{ matrix.pre-command }}
        python -m pip install --upgrade pip
        python -m pip install -U .[dev]

    - name: test
      run: |
          pytest --verbose --cov=desktop-notifier --cov-report=xml

    - name: upload code coverage
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: pytest
        env_vars: OS,PYTHON,TYPE
        name: pytests
        token: ${{ secrets.CODECOV_TOKEN }}
      env:
        OS: ${{ matrix.platform }}
        PYTHON: ${{ matrix.python-version }}
